### ISSUE TITLE
Meteor._wrapAsync has been renamed to Meteor.wrapAsync

### ISSUE THREAD

**Issue by steve-ross** [yogiben/meteor-starter#63]
Looks like the latest version of meteor breaks this app after you try to register the app restarts and this is printed in the console:

```
[[[[[ ~/starter ]]]]]                         

=> Started proxy.                             
=> Started MongoDB.                           
I20150505-17:54:45.424(-4)? Meteor._wrapAsync has been renamed to Meteor.wrapAsync
=> Exited with code: 8
W20150505-17:54:45.492(-4)? (STDERR) 
W20150505-17:54:45.492(-4)? (STDERR) events.js:72
W20150505-17:54:45.492(-4)? (STDERR)         throw er; // Unhandled 'error' event
W20150505-17:54:45.493(-4)? (STDERR)               ^
W20150505-17:54:45.493(-4)? (STDERR) Error: Command failed: gm identify: Unable to load module ("/usr/local/Cellar/graphicsmagick/1.3.18/lib/GraphicsMagick/modules-Q8/coders/png.la: file not found") [No such file or directory].
W20150505-17:54:45.493(-4)? (STDERR) gm identify: Request did not return an image.
W20150505-17:54:45.493(-4)? (STDERR)          
W20150505-17:54:45.493(-4)? (STDERR)     at ChildProcess._spawn.proc.on.onExit (/Users/sross/.meteor/packages/cfs_graphicsmagick/.0.0.18.5443uq++os+web.browser+web.cordova/npm/node_modules/gm/lib/command.js:279:17)
W20150505-17:54:45.493(-4)? (STDERR)     at ChildProcess.emit (events.js:98:17)
W20150505-17:54:45.493(-4)? (STDERR)     at maybeClose (child_process.js:766:16)
W20150505-17:54:45.494(-4)? (STDERR)     at Socket.<anonymous> (child_process.js:979:11)
W20150505-17:54:45.494(-4)? (STDERR)     at Socket.emit (events.js:95:17)
W20150505-17:54:45.494(-4)? (STDERR)     at Pipe.close (net.js:466:12)
fish: Job 1, 'meteor' terminated by signal SIGINT (Quit request from job control (^C))
```

**Comment by mpowaga** [comment]
This is problem with GraphicsMagick. Seems that png module is not installed.
