### ISSUE TITLE
Load order bug: comments and matb33:collection-hooks packages

### ISSUE THREAD

**Issue by brylie** [yogiben/meteor-starter#84]
There are a few open bugs describing an indirect error involving Tabular. 

```
Error: Tabular.Table options must specify collection
     at new Tabular.Table (packages/aldeed:tabular/common.js:20:1)
     at packages/yogiben:admin/lib/both/startup.coffee:100:27
     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
     at adminCreateTables (packages/yogiben:admin/lib/both/startup.coffee:77:4)
     at __coffeescriptShare (packages/yogiben:admin/lib/both/startup.coffee:178:2)
     at /home/.../.meteor/local/build/programs/server/boot.js:229:5
```
After troubleshooting the error, I found that it can be resolved by editing `.meteor/packages` and placing `matb33:collection-hooks` above the `comments` package.

**Comment by brylie** [comment]
I have created the following, for demonstration purposes:
* [basic fork and reproduction](https://github.com/brylie/meteor-starter-bug-84/tree/bug-84-reproduce)
* [reproduction with collection-hooks below comments](https://github.com/brylie/meteor-starter-bug-84/tree/bug-84-broken)
* [fix with collection-hooks above comments](https://github.com/brylie/meteor-starter-bug-84/tree/bug-84-fix)

**Comment by brylie** [comment]
Here is a [diff comparing the broken and fixed](https://github.com/brylie/meteor-starter-bug-84/compare/bug-84-broken...brylie:bug-84-fixed?expand=1) versions.

**Comment by matb33** [comment]
I had figured this out for someone else not long ago... Sorry you had to go through this debugging exercise as well... https://github.com/matb33/meteor-collection-hooks/issues/125#issuecomment-109015219

**Comment by artgo** [comment]
I don't have `comments` package for Meteor 1.3 :( what do I do, @brylie ?
